name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Obtendo o código
        uses: actions/checkout@v4

      - name: Set up QEMU  (necessário para multi-plataforma)
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx (necessário para multi-plataforma)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construção e envio da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          platforms:  |
            linux/amd64
            linux/arm64
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            roncoleta/devops4dev-review:v${{ github.run_number }}
            roncoleta/devops4dev-review:latest

       
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:         
      - name: Obtendo o código
        uses: actions/checkout@v4

      - name: Configuração do kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Execução do kubectl apply
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: |
            roncoleta/devops4dev-review:v${{ github.run_number }}

    