name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Passo 01
        run: echo "Execução do build da imagem"
      - name: Passo 02
        run: echo "Execução do push da imagem"        
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:         
      - name: Passo 01
        run: echo "Execução do Deploy"
